# Set some variables for convenience
substitutions:
  node_name: rs485
  device_name: rs485 modbus
  device_description: "connect serial device"

esphome:
  name: $node_name
  comment: '${device_description}'
  platform: ESP32
  board: nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.168
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "rs485 Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${node_name}_espversion
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${node_name}_ip
    ssid:
      name: ${node_name}_ssid
    bssid:
      name: ${node_name}_bssid

###############################################################

# A reboot button is always useful
button:
  - platform: restart
    name: ${node_name}_restart

switch:
  - platform: gpio
    name: ${node_name}_onboard_led
    pin: GPIO2
    id: blue_led

################# CWT-TH03S #################################################

uart:
  id: mod_uart
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 4800
  stop_bits: 1

modbus:
  send_wait_time: 1000ms
  uart_id: mod_uart
  id: modbus1

modbus_controller:
  - id: rs485
    address: 1
    modbus_id: modbus1

###################################################################

sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${node_name}_uptime
    update_interval: 60s

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${node_name}_wifisignal
    update_interval: 60s

############ MODBUS ###################################################

  - platform: modbus_controller
    modbus_controller_id: rs485
    name: "Hum"
    id: hum
    register_type: holding
    address: 0x0000
    unit_of_measurement: "%"
    value_type: U_WORD
    filters:
      - multiply: 0.1
    accuracy_decimals: 1
    icon: "mdi:water-percent"
    device_class: "humidity"
    state_class: "measurement"

  - platform: modbus_controller
    modbus_controller_id: rs485
    name: "Temp"
    id: temp
    register_type: read
    address: 0x0001
    unit_of_measurement: "°"
    value_type: U_WORD
    filters:
      - multiply: 0.1
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    device_class: "temperature"
    state_class: "measurement"